from sqlalchemy import Column, Float, Integer, String, Text

from app.models.base_models import BaseModel


class Signal(BaseModel):
    """
    Represents a trading signal generated by the AI.

    Attributes:
        ticker: Stock symbol (e.g., "TATASTEEL", "RELIANCE")
        action: Trading action (BUY, SELL, HOLD)
        confidence: Confidence score (0-100)
        entry_price: Entry price for the trade
        target_price: Target price for profit
        stop_loss: Stop loss price
        reasoning: AI's explanation for the signal
        source_url: Source URL for the signal
    """

    __tablename__ = "signals"

    ticker = Column(String, index=True, nullable=False)
    action = Column(String, nullable=False)
    confidence = Column(Integer, nullable=False)

    entry_price = Column(Float, nullable=False)
    target_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)

    reasoning = Column(Text, nullable=False)
    source_url = Column(String, nullable=True)
